export const CONFIG_SUCCESS = "CONFIG_SUCCESS";
export const POPULAR_DATA_SUCCESS = "POPULAR_DATA_SUCCESS";
export const IMG_DATA_FAILED = "IMG_DATA_FAILED";

export const NOW_PLAYING_DATA_SUCCESS = "NOW_PLAYING_DATA_SUCCESS";
export const NOW_PLAYING_DATA_FAILED = "NOW_PLAYING_FAILED";

export const TOP_RATED_DATA_SUCCESS = "TOP_RATED_DATA_SUCCESS";
export const TOP_RATED_DATA_FAILED = "TOP_RATED_DATA_FAILED";
