export const IMG_CONFIG_SUCCESS = "IMG_CONFIG_SUCCESS";
export const IMG_GET_POPULAR_SUCCESS = "IMG_GET_POPULAR_SUCCESS";
export const IMG_DATA_FAILED = "IMG_DATA_FAILED";

export const IMG_GET_NOW_PLAYING_SUCCESS = "IMG_GET_NOW_PLAYING_SUCCESS";
export const IMG_GET_NOW_PLAYING_FAILED = "IMG_GET_NOW_PLAYING_FAILED";
