export const CONFIG_SUCCESS = "CONFIG_SUCCESS";
export const POPULAR_DATA_SUCCESS = "POPULAR_DATA_SUCCESS";
export const IMG_DATA_FAILED = "IMG_DATA_FAILED";

export const NOW_PLAYING_DATA_SUCCESS = "NOW_PLAYING_DATA_SUCCESS";
export const NOW_PLAYING_DATA_FAILED = "NOW_PLAYING_FAILED";

export const TOP_RATED_DATA_SUCCESS = "TOP_RATED_DATA_SUCCESS";
export const TOP_RATED_DATA_FAILED = "TOP_RATED_DATA_FAILED";

export const MOVIE_DETAIL_SUCCESS = "MOVIE_DETAIL_SUCCESS";
export const MOVIE_DETAIL_FAILED = "MOVIE_DETAIL_FAILED";

export const CAST_SUCCESS = "CAST_SUCCESS";
export const CAST_FAILED = "CAST_FAILED";

export const ACTOR_DETAILS_SUCCESS = "ACTOR_DETAILS_SUCCESS";
export const ACTOR_DETAILS_FAILED = "ACTOR_DETAILS_FAILED";

export const ACTOR_MOVIES_SUCCESS = "ACTOR_MOVIES_SUCCESS";
export const ACTOR_MOVIES_FAILED = "ACTOR_MOVIES_FAILED";

/// pagination

export const POP_SUCCESS = "POP_SUCCESS";
export const POP_FAILED = "POP_FAILED";

export const NOW_SUCCESS = "NOW_SUCCESS";
export const NOW_FAILED = "NOW_FAILED";

export const TOP_SUCCESS = "TOP_SUCCESS";
export const TOP_FAILED = "TOP_FAILED";

export const SUGGESTION_SUCCESS = "SUGGESTION_SUCCESS";
export const SUGGESTION_FAILED = "SUGGESTION_FAILED";
export const SUGGESTION_CLEAR = "SUGGESTION_CLEAR";
